apiVersion: apps/v1
kind: Deployment
metadata:
  name: notesapi-deployment
spec:
  selector:
    matchLabels:
      app: notesapi
  replicas: 1
  template:
    metadata:
      labels:
        app: notesapi
    spec:
      containers:
        - name: notesapi-container
          image: laaksomavrick/notes:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
